import 'package:qismati/common/models/profile.dart';

List<ProfileModel> profiles = [
  ProfileModel(
    location: Location(
      coordinates: [38.770355, 9.060475],
      type: "Point",
    ),
    id: "1",
    userName: "Mohammed",
    fullName: "Mohammed Alshammari",
    email: "mohammed@example.com",
    phoneNumber: "+966 123456789",
    age: 28,
    gender: "Male",
    height: 175,
    weight: 70,
    skinColor: "Fair",
    bodyShape: "Average",
    healthCase: "Diabetes",
    smoking: false,
    prayer: true,
    religiousCommitment: true,
    maritalStatus: "Single",
    marriageType: "Islamic",
    children: 0,
    educationalQualification: "Bachelor",
    jobCategory: "Software Engineer",
    job: "Developer",
    monthlyIncome: 5000,
    financialStatus: "Good",
    nationality: "Saudi",
    city: "Riyadh",
    country: "Saudi Arabia",
    aboutYourSelf: "I am a software engineer with 5 years of experience",
    aboutYourPartner: "I am looking for a good and kind partner",
    beard: "Yes",
    viel: "Yes",
    lastVerificationEmailSentOn: DateTime.now(),
    isDeleted: false,
    isBanned: false,
    isVerified: true,
    appearOnSearch: true,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProfileModel(
    location: Location(
      coordinates: [38.770355, 9.060475],
      type: "Point",
    ),
    id: "2",
    userName: "Ahmed",
    fullName: "Ahmed Alzahrani",
    email: "ahmed@example.com",
    phoneNumber: "+966 987654321",
    age: 30,
    gender: "Male",
    height: 180,
    weight: 75,
    skinColor: "Dark",
    bodyShape: "Muscular",
    healthCase: "None",
    smoking: false,
    prayer: true,
    religiousCommitment: true,
    maritalStatus: "Married",
    marriageType: "Islamic",
    children: 2,
    educationalQualification: "Master",
    jobCategory: "Doctor",
    job: "Physician",
    monthlyIncome: 10000,
    financialStatus: "Excellent",
    nationality: "Egyptian",
    city: "Jeddah",
    country: "Saudi Arabia",
    aboutYourSelf: "I am a doctor with 10 years of experience",
    aboutYourPartner: "I am looking for a good and kind partner",
    beard: "No",
    viel: "No",
    lastVerificationEmailSentOn: DateTime.now(),
    isDeleted: false,
    isBanned: false,
    isVerified: true,
    appearOnSearch: true,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProfileModel(
    location: Location(
      coordinates: [38.770355, 9.060475],
      type: "Point",
    ),
    id: "3",
    userName: "Ali",
    fullName: "Ali Alhajri",
    email: "ali@example.com",
    phoneNumber: "+966 555555555",
    age: 25,
    gender: "Male",
    height: 160,
    weight: 60,
    skinColor: "Fair",
    bodyShape: "Average",
    healthCase: "None",
    smoking: false,
    prayer: true,
    religiousCommitment: true,
    maritalStatus: "Single",
    marriageType: "Islamic",
    children: 0,
    educationalQualification: "Bachelor",
    jobCategory: "Student",
    job: "Student",
    monthlyIncome: 2000,
    financialStatus: "Good",
    nationality: "Yemeni",
    city: "Makkah",
    country: "Saudi Arabia",
    aboutYourSelf:
        "I am a student and I am looking for a good and kind partner",
    aboutYourPartner: "I am looking for a good and kind partner",
    beard: "Yes",
    viel: "Yes",
    lastVerificationEmailSentOn: DateTime.now(),
    isDeleted: false,
    isBanned: false,
    isVerified: true,
    appearOnSearch: true,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  ProfileModel(
    location: Location(
      coordinates: [38.770355, 9.060475],
      type: "Point",
    ),
    id: "4",
    userName: "Fatima",
    fullName: "Fatima Alghamdi",
    email: "fatima@example.com",
    phoneNumber: "+966 666666666",
    age: 27,
    gender: "Female",
    height: 168,
    weight: 65,
    skinColor: "Fair",
    bodyShape: "Average",
    healthCase: "None",
    smoking: false,
    prayer: true,
    religiousCommitment: true,
    maritalStatus: "Single",
    marriageType: "Islamic",
    children: 0,
    educationalQualification: "Bachelor",
    jobCategory: "Nurse",
    job: "Nurse",
    monthlyIncome: 3000,
    financialStatus: "Good",
    nationality: "Saudi",
    city: "Madinah",
    country: "Saudi Arabia",
    aboutYourSelf: "I am a nurse and I am looking for a good and kind partner",
    aboutYourPartner: "I am looking for a good and kind partner",
    beard: "No",
    viel: "No",
    lastVerificationEmailSentOn: DateTime.now(),
    isDeleted: false,
    isBanned: false,
    isVerified: true,
    appearOnSearch: true,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
