on:
  push:
    branches:
      - main

name: Build and Release

jobs:
  build:
    name: Build and Release new application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      
      - name: Push App Build to Releases
        uses: softprops/action-gh-release@v1
        with:
          files : |
            build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
